name: Build APK from ZIP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar herramientas necesarias
        run: sudo apt-get install unzip -y

      - name: Descomprimir proyecto
        run: unzip SDIIN_CONEX.zip -d SDIIN_CONEX

      - name: Dar permisos a gradlew
        run: chmod +x SDIIN_CONEX/gradlew

      - name: Compilar APK
        working-directory: SDIIN_CONEX
        run: ./gradlew assembleDebug

      - name: Subir APK compilado
        uses: actions/upload-artifact@v3
        with:
          name: SDIIN-CONEX-APK
          path: SDIIN_CONEX/app/build/outputs/apk/debug/app-debug.apk
